---
###############################################################
# Decide if the [ClearInvntory, Gamemode, FallDamage, NoHunger] should be emptied for each join.
# Use "true" for activate or "false" for deactivate.
Player-Join:
  ClearInv: true
  Gamemode:
    # NOTE: if set 'true' you can set gamemode player join.
    Enable: true
    # Format = [SURVIVAL = 0, CREATIVE = 1]
    #          [ADVENTURE = 2, SPECTATOR = 3]
    setGamemode: 0
  NoFallDamage: false
  NoHunger: false
  
  # This is setting to custom hunger & heal for player
  # Use "true" for activate or "false" for deactivate.
  Hunger-Heal:
    Enable: true
    Heal: 20    # Max set Heal 20
    Hunger: 20  # Max set Hunger 20
  
# Setting Message.
# Use {player} to replace the player name
# Use '&' to replace text format color
# Use '\n' to side new line
Welcome-Message:
  Enable: true
  Message: "&l&d♠ &bWelcome &l&b{player} &r&7to &eName Server"
Welcome-Popup: 
  Enable: true
  Message: "&aWelcome &f{player}"

###############################################################
...
